/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as CoursesImport } from './routes/courses'
import { Route as AboutImport } from './routes/about'
import { Route as IndexImport } from './routes/index'
import { Route as CoursesCourseIdImport } from './routes/courses.$courseId'
import { Route as CoursesCourseIdLessonsImport } from './routes/courses.$courseId.lessons'
import { Route as CoursesCourseIdLessonsLessonIdImport } from './routes/courses.$courseId.lessons.$lessonId'

// Create/Update Routes

const CoursesRoute = CoursesImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRoute,
} as any)

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const CoursesCourseIdRoute = CoursesCourseIdImport.update({
  id: '/$courseId',
  path: '/$courseId',
  getParentRoute: () => CoursesRoute,
} as any)

const CoursesCourseIdLessonsRoute = CoursesCourseIdLessonsImport.update({
  id: '/lessons',
  path: '/lessons',
  getParentRoute: () => CoursesCourseIdRoute,
} as any)

const CoursesCourseIdLessonsLessonIdRoute =
  CoursesCourseIdLessonsLessonIdImport.update({
    id: '/$lessonId',
    path: '/$lessonId',
    getParentRoute: () => CoursesCourseIdLessonsRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesImport
      parentRoute: typeof rootRoute
    }
    '/courses/$courseId': {
      id: '/courses/$courseId'
      path: '/$courseId'
      fullPath: '/courses/$courseId'
      preLoaderRoute: typeof CoursesCourseIdImport
      parentRoute: typeof CoursesImport
    }
    '/courses/$courseId/lessons': {
      id: '/courses/$courseId/lessons'
      path: '/lessons'
      fullPath: '/courses/$courseId/lessons'
      preLoaderRoute: typeof CoursesCourseIdLessonsImport
      parentRoute: typeof CoursesCourseIdImport
    }
    '/courses/$courseId/lessons/$lessonId': {
      id: '/courses/$courseId/lessons/$lessonId'
      path: '/$lessonId'
      fullPath: '/courses/$courseId/lessons/$lessonId'
      preLoaderRoute: typeof CoursesCourseIdLessonsLessonIdImport
      parentRoute: typeof CoursesCourseIdLessonsImport
    }
  }
}

// Create and export the route tree

interface CoursesCourseIdLessonsRouteChildren {
  CoursesCourseIdLessonsLessonIdRoute: typeof CoursesCourseIdLessonsLessonIdRoute
}

const CoursesCourseIdLessonsRouteChildren: CoursesCourseIdLessonsRouteChildren =
  {
    CoursesCourseIdLessonsLessonIdRoute: CoursesCourseIdLessonsLessonIdRoute,
  }

const CoursesCourseIdLessonsRouteWithChildren =
  CoursesCourseIdLessonsRoute._addFileChildren(
    CoursesCourseIdLessonsRouteChildren,
  )

interface CoursesCourseIdRouteChildren {
  CoursesCourseIdLessonsRoute: typeof CoursesCourseIdLessonsRouteWithChildren
}

const CoursesCourseIdRouteChildren: CoursesCourseIdRouteChildren = {
  CoursesCourseIdLessonsRoute: CoursesCourseIdLessonsRouteWithChildren,
}

const CoursesCourseIdRouteWithChildren = CoursesCourseIdRoute._addFileChildren(
  CoursesCourseIdRouteChildren,
)

interface CoursesRouteChildren {
  CoursesCourseIdRoute: typeof CoursesCourseIdRouteWithChildren
}

const CoursesRouteChildren: CoursesRouteChildren = {
  CoursesCourseIdRoute: CoursesCourseIdRouteWithChildren,
}

const CoursesRouteWithChildren =
  CoursesRoute._addFileChildren(CoursesRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/courses': typeof CoursesRouteWithChildren
  '/courses/$courseId': typeof CoursesCourseIdRouteWithChildren
  '/courses/$courseId/lessons': typeof CoursesCourseIdLessonsRouteWithChildren
  '/courses/$courseId/lessons/$lessonId': typeof CoursesCourseIdLessonsLessonIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/courses': typeof CoursesRouteWithChildren
  '/courses/$courseId': typeof CoursesCourseIdRouteWithChildren
  '/courses/$courseId/lessons': typeof CoursesCourseIdLessonsRouteWithChildren
  '/courses/$courseId/lessons/$lessonId': typeof CoursesCourseIdLessonsLessonIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/courses': typeof CoursesRouteWithChildren
  '/courses/$courseId': typeof CoursesCourseIdRouteWithChildren
  '/courses/$courseId/lessons': typeof CoursesCourseIdLessonsRouteWithChildren
  '/courses/$courseId/lessons/$lessonId': typeof CoursesCourseIdLessonsLessonIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/courses'
    | '/courses/$courseId'
    | '/courses/$courseId/lessons'
    | '/courses/$courseId/lessons/$lessonId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/courses'
    | '/courses/$courseId'
    | '/courses/$courseId/lessons'
    | '/courses/$courseId/lessons/$lessonId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/courses'
    | '/courses/$courseId'
    | '/courses/$courseId/lessons'
    | '/courses/$courseId/lessons/$lessonId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CoursesRoute: typeof CoursesRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CoursesRoute: CoursesRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/courses"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/courses": {
      "filePath": "courses.tsx",
      "children": [
        "/courses/$courseId"
      ]
    },
    "/courses/$courseId": {
      "filePath": "courses.$courseId.tsx",
      "parent": "/courses",
      "children": [
        "/courses/$courseId/lessons"
      ]
    },
    "/courses/$courseId/lessons": {
      "filePath": "courses.$courseId.lessons.tsx",
      "parent": "/courses/$courseId",
      "children": [
        "/courses/$courseId/lessons/$lessonId"
      ]
    },
    "/courses/$courseId/lessons/$lessonId": {
      "filePath": "courses.$courseId.lessons.$lessonId.tsx",
      "parent": "/courses/$courseId/lessons"
    }
  }
}
ROUTE_MANIFEST_END */
